---
name: 'Setup Docker Build Environment'
description: 'Prepare Docker build environment with Buildx and GHCR login'
author: 'Minitrino'

inputs:
  github-token:
    description: 'GitHub token for GHCR authentication'
    required: true
  cleanup-disk:
    description: 'Whether to free up disk space'
    required: false
    default: 'true'

outputs:
  trino-version:
    description: 'Trino version from minitrino.env'
    value: ${{ steps.version.outputs.trino_version }}
  starburst-version:
    description: 'Starburst version from minitrino.env'
    value: ${{ steps.version.outputs.starburst_version }}

runs:
  using: 'composite'
  steps:
    - name: Check out code
      uses: actions/checkout@v5

    - name: Free up disk space
      if: inputs.cleanup-disk == 'true'
      uses: ./.github/actions/cleanup-disk

    - name: Get cluster version
      id: version
      uses: ./.github/actions/get-cluster-version

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}
