---
name: 'Setup Test Environment'
description: 'Setup Python, install dependencies, and wait for test release'
author: 'Minitrino'

inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true
  python-version:
    description: 'Python version to install'
    required: false
    default: '3.10'
  install-test-dependencies:
    description: 'Whether to install test dependencies (src/tests/)'
    required: false
    default: 'true'
  setup-license:
    description: 'Whether to setup Starburst license file'
    required: false
    default: 'false'
  license-data:
    description: 'Starburst license data (required if setup-license is true)'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Wait for test release
      uses: ./.github/actions/wait-for-test-release
      with:
        github-token: ${{ inputs.github-token }}

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install CLI dependencies
      shell: bash
      run: pip install -e .

    - name: Install test dependencies
      if: inputs.install-test-dependencies == 'true'
      shell: bash
      run: pip install -e ./src/tests/

    - name: Export Python bin to PATH
      shell: bash
      run: |
        # Add Python bin directory to PATH for subsequent steps
        PYTHON_BIN="$(python -c 'import sys; print(sys.prefix)')/bin"
        echo "$PYTHON_BIN" >> $GITHUB_PATH
        echo "Python bin directory exported to PATH: $PYTHON_BIN"

    - name: Set up Starburst license
      if: inputs.setup-license == 'true'
      shell: bash
      run: echo "${{ inputs.license-data }}" > ~/starburstdata.license
