name: Library Tests

on:
  pull_request:
    branches:
      - master
    paths:
      - src/lib/**

jobs:
  lib-tests:
    runs-on: ubuntu-22.04
    steps:

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'      

    - name: Check out code
      uses: actions/checkout@v4

    - name: Install project dependencies
      run: |-
        pip install --editable ./src/cli/
        pip install --editable ./src/test/

    - name: Write config file and point to license
      run: |-
        echo "${LIC_DATA}" > ~/starburstdata.license
        mkdir ~/.minitrino/
        cat <<EOF > ~/.minitrino/minitrino.cfg
        [config]
        LIC_PATH=~/starburstdata.license
        EOF
      env:
          LIC_DATA: ${{ secrets.LIC_DATA }}

    - name: Run library tests
      run: |-
        python ./src/test/src/lib/runner.py
